### ISSUE TITLE
Error while running mvn install on appsensor directory

### ISSUE THREAD

**Issue by shreyasdn** [jtmelton/appsensor#33]
I am facing this error when running install command on the appsensor directory. Kindly let me know if there is a fix for this.

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.579 sec <<< FA
ILURE! - in org.owasp.appsensor.integration.cef.syslog.CefSyslogEmitterEventTest

testAttackCreation(org.owasp.appsensor.integration.cef.syslog.CefSyslogEmitterEv
entTest)  Time elapsed: 1.329 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at org.owasp.appsensor.local.analysis.ReferenceStatisticalEventAnalysisE
ngineTest.testAttackCreation(ReferenceStatisticalEventAnalysisEngineTest.java:12
0)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMetho
dCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethod
Callbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evalu
ate(SpringRepeat.java:72)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runCh
ild(SpringJUnit4ClassRunner.java:232)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runCh
ild(SpringJUnit4ClassRunner.java:89)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.
java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClass
Callbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassC
allbacks.evaluate(RunAfterTestClassCallbacks.java:71)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(S
pringJUnit4ClassRunner.java:175)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)

**Comment by ProZachJ** [comment]
What command did you use?

**Comment by jtmelton** [comment]
Also, do you already have appsensor installed or is this your first attempt? Did the instructions under the "Building" section of the README work successfully? 

I tried running this command on a fresh copy _after_ doing the steps from the "Building" section and it worked just fine. 

The other question I'd like to ask is if this has been repeatable. It's slightly possible that since this is mongo we're getting a delta between the write time and the read time. I can put a slight delay in place to make sure that's not the case, but I'd like to see if the error happens repeatedly first. Could just be a fluke (note: this has never failed for us before)

**Comment by shreyasdn** [comment]
I have used mvn install. should i use mvn test instead?

**Comment by shreyasdn** [comment]
I have performed all the steps from the "Building" section of the README  and it works fine. but used mvn install instead of mvn test.

**Comment by jtmelton** [comment]
ok, mvn install vs. test shouldn't make a difference - they do very similar things, just install additionally places the generated jar files in your local repository on disk. 

Did it succeed or fail this time?

**Comment by shreyasdn** [comment]
it succeeds for mvn test but fails at same place for mvn install. Which makes no sense but closing because it succeeds for mvn test

**Comment by jtmelton** [comment]
yeah, that's very odd - it's probably worth trying 4 or 5 times to make sure it's repeatable, but I'm not aware of any reason that should make any difference. It certainly makes no difference to our code, but beyond that, whether or not something is installed has absolutely no bearing on the place it's failing in the code. Thanks for working through this with us!
